datasource:
  driverClassName: org.h2.Driver
  password: changeme
  #url: jdbc:h2:file:./database-h2
  # To connect from sql client: jdbc:h2:tcp://localhost:8082/mem:database-h2
  url: jdbc:h2:mem:database-h2
  username: dkt
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  defer-datasource-initialization: true
  hibernate:
    ddl-auto: create-drop

## LOGS ##
logging:
  config: classpath:logback.xml
  filter:
    enabled: false
  level:
    httpclient:
      wire: ERROR
    org:
      apache:
        http: ERROR
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ERROR
        web:
          filter:
            CommonsRequestLoggingFilter: ERROR